# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    name: Build the code
    steps:
      - name: Run unit tests
        id: unittests
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          file-name: FrontEnd/package.json
          node-version: ${{ matrix.node }}
      - name: Run unit tests
        run: cd FrontEnd; yarn test
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.unittests.outputs.time }}"

